name: Update README Dates

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-dates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set current date
        id: date
        run: echo "date=$(date '+%B %Y')" >> $GITHUB_OUTPUT

      - name: Update certification date
        run: |
          sed -i 's/Last updated: .* 路 <!-- cert-date -->/Last updated: ${{ steps.date.outputs.date }} 路 <!-- cert-date -->/' README.md

      - name: Update footer date
        run: |
          sed -i 's/Last updated: .* 路 All assets and badges are locally sourced or verified<\/em><\/sub> <!-- footer-date -->/Last updated: ${{ steps.date.outputs.date }} 路 All assets and badges are locally sourced or verified<\/em><\/sub> <!-- footer-date -->/' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-update README dates"
          git push


